### ISSUE TITLE
config in: ros/src/camera_info_publisher/yaml_to_camera_info_publisher.py

### ISSUE THREAD

**Issue by chaliburton** [chaliburton/CarND-Capstone#12]
two configuration values needed for each of two variables:
1. line 62 set queue_size=2 to a config, 2 for simulator, 10 for CARLA
2. line 63 set rate(2)  to a config, 2 for simulator, 10 for CARLA

**Comment by ristovtodor** [comment]
Hmm not sure if we need to make anything configurable? Seems like this file is run as a standalone script, so I guess we can modify parameters there directly depending on where we want to run it. Is this script even used by udacity in their grading process?

**Comment by chaliburton** [comment]
reverted to 10 to match initial code
